name: Build iOS IPA & Android APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS No-Codesign IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r BSMS_iOS_Test.ipa Payload

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSMS_iOS_Test.ipa
          path: build/ios/iphoneos/BSMS_iOS_Test.ipa

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSMS_Android_v2.apk
          path: build/app/outputs/flutter-apk/app-release.apk
